name: Build EXE
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Create EXE
      run: pyinstaller --noconsole --onefile steam_fixer.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SteamFixer-Programa
        path: dist/steam_fixer.exe
