name: Build EXE
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar PyInstaller
      run: pip install pyinstaller
    - name: Compilar a EXE
      run: pyinstaller --noconsole --onefile steam_fixer.py
    - name: Subir el EXE
      uses: actions/upload-artifact@v3
      with:
        name: SteamFixer-Programa
        path: dist/steam_fixer.exe
